apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: "hotserver"
  labels:
    app: "hotserver"
spec:
  selector:
    matchLabels:
      app: "hotserver"
  replicas: 1
  template:
    metadata:
      labels:
        app: "hotserver"
    spec:
      containers:
      - name: "hotserver"
        image: fernandolerma/esquenta-k8s-live:v2